name: Python CICD
run-name: ${{ github.actor }} triggered workflow ${{ github.workflow }} from branch ${{ github.ref }}
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: pip install nbconvert ipykernel
      # - uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: pandoc texlive-xetex texlive-fonts-recommended inkscape
      #     version: 1.0
      - run: sudo apt-get install pandoc inkscape texlive-xetex texlive-fonts-recommended
      - run: |
          for file in $(find lab* -type f -name "*.ipynb"); do
            python -m nbconvert --to pdf --execute "$file"
          done
      - uses: actions/upload-artifact@v4
        with:
          path: lab*/*.pdf