name: Python CICD
run-name: ${{ github.actor }} triggered workflow ${{ github.workflow }} from branch ${{ github.ref }}
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Nbconvert setup
        run: pip install nbconvert

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-cache

      - name: Install pandoc & texlive
        run: sudo apt-get install pandoc inkscape texlive-xetex

      - name: All ipynb to pdf
        run: |
          for file in **/*.ipynb; do
            jupyter nbconvert --execute --to pdf "$file"
          done

      - name: Upload rendered PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rendered-pdfs
          path: '**/*.pdf'