name: Python CICD
run-name: ${{ github.actor }} triggered workflow ${{ github.workflow }} from branch ${{ github.ref }}
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Nbconvert setup
        run: pip install nbconvert

      - name: Cache apt
        id: cache-apt-installation
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/apt_install_cache
          key: ${{ runner.os }}-apt-install-cache

      - name: Install pandoc, inkscape & texlive-xetex from cache
        env:
          CACHE_HIT: ${{ steps.cache-apt-installation.outputs.cache-hit }}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive $HOME/apt_install_cache/* /
          else
            sudo apt-get install --yes pandoc inkscape texlive-xetex
            mkdir -p $HOME/apt_install_cache
            for pkg in pandoc inkscape texlive-xetex; do
              sudo dpkg -L "$pkg" | while IFS= read -r f; do
                if test -f "$f"; then echo "$f"; fi;
              done | xargs cp --parents --target-directory $HOME/apt_install_cache/
            done
          fi

      - name: All ipynb to pdf
        run: |
          for file in **/*.ipynb; do
            jupyter nbconvert --execute --to pdf "$file"
          done

      - name: Upload rendered PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rendered-pdfs
          path: '**/*.pdf'