name: Python CICD
run-name: ${{ github.actor }} triggered workflow ${{ github.workflow }} from branch ${{ github.ref }}
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Python setup
        run: pip install nbconvert 

      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: All ipynb to pdf
        uses: actions/checkout@v5
        run: |
          for file in *.ipynb; do
            jupyter nbconvert --to pdf "$file"
          done


      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Run all ipynb files
      #   run: |
      #     for file in *.ipynb; do
      #       jupyter nbconvert --to notebook --execute "$file" --inplace
      #     done
      
      # - name: save all ipynb files to pdf
      #   run: |
      #     for file in *.ipynb; do
      #       jupyter nbconvert --to pdf "$file"
      #     done
